name: Continous Integration and Deployment # name of process

on: # when process run
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "5.0.x"
  AZURE_WEBAPP_NAME: giangappservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code # just a name
        uses: actions/checkout@v3 # get from marketplace

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore packages
        run: dotnet restore

      - name: Build .NET application
        run: dotnet build -c Release --no-restore

      - name: Run Unit Test
        run: dotnet test -c Release --no-build

      - name: SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      - name: SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}

      - name: Publish app
        run: dotnet publish -c Release -o ./out # publish to ./out folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # web app name created in Azure Portal
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_SECRECT }} # secrets. name of secrets created in github
          package: ./out # read published files int ./out
